name: bpm
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  firebase_core: ^2.22.0
  cloud_firestore: ^4.13.1
  firebase_auth: ^4.14.0
  font_awesome_flutter: ^10.6.0
  equatable: ^2.0.5
  logger: ^2.0.2+1
  firebase_crashlytics: ^3.4.4
  injectable: ^2.3.2
  get_it: ^7.6.4
  connectivity_plus: ^5.0.1
  freezed_annotation: ^2.4.1
  easy_localization: ^3.0.3
  json_annotation: ^4.0.6
  shared_preferences: ^2.2.2
  modal_bottom_sheet: ^2.1.2
  flutter_easyloading: ^3.0.5
  geolocator: ^10.1.0
  dots_indicator: ^3.0.0
  image_picker: ^1.0.4
  firebase_storage: ^11.5.3
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  lint: ^2.2.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1

dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/translations/
    - android/
    - android/app/
    - android/app/src/
    - android/app/src/main/
    - android/app/src/main/res/
    - android/app/src/main/res/values/
    - android/app/src/main/res/drawable/
    - android/app/src/main/res/mipmap-hdpi/
    - android/app/src/main/res/mipmap-mdpi/
    - android/app/src/main/res/drawable-v21/
    - android/app/src/main/res/mipmap-xhdpi/
    - android/app/src/main/res/values-night/
    - android/app/src/main/res/mipmap-xxhdpi/
    - android/app/src/main/res/mipmap-xxxhdpi/
    - android/app/src/main/java/
    - android/app/src/main/java/io/
    - android/app/src/main/java/io/flutter/
    - android/app/src/main/java/io/flutter/plugins/
    - android/app/src/main/kotlin/
    - android/app/src/main/kotlin/com/
    - android/app/src/main/kotlin/com/bpm/
    - android/app/src/main/kotlin/com/bpm/bpm/
    - android/app/src/debug/
    - android/app/src/profile/
    - android/gradle/
    - android/gradle/wrapper/
    - android/.gradle/
    - android/.gradle/7.5/
    - android/.gradle/7.5/checksums/
    - android/.gradle/7.5/fileHashes/
    - android/.gradle/7.5/fileChanges/
    - android/.gradle/7.5/vcsMetadata/
    - android/.gradle/7.5/executionHistory/
    - android/.gradle/7.5/dependencies-accessors/
    - android/.gradle/vcs-1/
    - android/.gradle/buildOutputCleanup/
    - lib/signup/domain/usecases/

