name: assoshare
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #https://pub.dev/packages/cupertino_icons
  cupertino_icons: ^1.0.8

  #https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^8.1.6

  #FIREBASE
  #https://pub.dev/packages/firebase_core
  firebase_core: ^3.8.0

  #https://pub.dev/packages/cloud_firestore
  cloud_firestore: ^5.5.0

  #https://pub.dev/packages/firebase_auth
  firebase_auth: ^5.3.2

  #https://pub.dev/packages/firebase_storage
  firebase_storage: ^12.3.6

  #https://pub.dev/packages/font_awesome_flutter
  font_awesome_flutter: ^10.8.0

  equatable: ^2.0.5
  logger: ^2.5.0
  firebase_crashlytics: ^4.1.4
  injectable: ^2.3.2
  get_it: ^7.6.4

  #https://pub.dev/packages/connectivity_plus
  connectivity_plus: ^6.1.0

  freezed_annotation: ^2.4.1
  easy_localization: ^3.0.3
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.2
  modal_bottom_sheet: ^2.1.2
  flutter_easyloading: ^3.0.5

  #https://pub.dev/packages/geolocator
  geolocator: ^13.0.2

  dots_indicator: ^3.0.0
  image_picker: ^1.0.4
  path: ^1.8.3
  photo_view: ^0.14.0
  uuid: ^4.2.2
  http: ^1.1.0
  permission_handler: ^11.0.1

  #https://pub.dev/packages/dio
  dio: ^5.7.0

  #https://pub.dev/packages/flutter_svg
  flutter_svg: ^2.0.15

  #https://pub.dev/packages/intl
  intl: ^0.19.0

  #https://pub.dev/packages/shimmer
  shimmer: ^3.0.0

  #https://pub.dev/packages/gap
  gap: ^3.0.1

  #https://pub.dev/packages/google_fonts
  google_fonts: ^6.2.1

  #https://pub.dev/packages/firebase_app_check
  firebase_app_check: ^0.3.1+7

  #https://pub.dev/packages/cached_network_image
  cached_network_image: ^3.4.1

  #https://pub.dev/packages/nested
  nested: ^1.0.0

  #https://pub.dev/packages/go_router
  go_router: ^14.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  lint: ^2.2.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  injectable_generator: ^2.4.1
  json_serializable: ^6.9.0
  change_app_package_name: ^1.4.0
  mockito: ^5.4.4
  bloc_test: ^9.1.6

dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - android/
    - android/app/
    - android/app/src/
    - android/app/src/main/
    - android/app/src/main/res/
    - android/app/src/main/res/values/
    - android/app/src/main/res/drawable/
    - android/app/src/main/res/mipmap-hdpi/
    - android/app/src/main/res/mipmap-mdpi/
    - android/app/src/main/res/drawable-v21/
    - android/app/src/main/res/mipmap-xhdpi/
    - android/app/src/main/res/values-night/
    - android/app/src/main/res/mipmap-xxhdpi/
    - android/app/src/main/res/mipmap-xxxhdpi/
    - android/app/src/main/java/
    - android/app/src/main/java/io/
    - android/app/src/main/java/io/flutter/
    - android/app/src/main/java/io/flutter/plugins/
    - android/app/src/main/kotlin/
    - android/app/src/main/kotlin/com/
    - android/app/src/main/kotlin/com/rennes/
    - android/app/src/debug/
    - android/app/src/profile/
    - android/gradle/
    - android/gradle/wrapper/
    - android/.gradle/
    - android/.gradle/vcs-1/
    - android/.gradle/buildOutputCleanup/

