// Mocks generated by Mockito 5.4.4 from annotations
// in assoshare/test/presentation/blocs/favorite/favorite_list_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:assoshare/domain/entities/favorite/favorite_entity.dart' as _i4;
import 'package:assoshare/domain/usecases/favorite/update_favorites_use_case.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UpdateFavoritesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateFavoritesUseCase extends _i1.Mock
    implements _i2.UpdateFavoritesUseCase {
  MockUpdateFavoritesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.FavoriteEntity>> call(
    Set<String>? newIds,
    List<_i4.FavoriteEntity>? currentFavorites,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            newIds,
            currentFavorites,
          ],
        ),
        returnValue:
            _i3.Future<List<_i4.FavoriteEntity>>.value(<_i4.FavoriteEntity>[]),
      ) as _i3.Future<List<_i4.FavoriteEntity>>);
}
