// Mocks generated by Mockito 5.4.4 from annotations
// in assoshare/test/presentation/blocs/search_ad/search_ad_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:assoshare/core/domain/entities/result.dart' as _i5;
import 'package:assoshare/domain/entities/ad/ad_entity.dart' as _i8;
import 'package:assoshare/domain/entities/ad/post_ad_entity.dart' as _i6;
import 'package:assoshare/domain/entities/filter/filter_entity.dart' as _i2;
import 'package:assoshare/domain/repositories/ad_repository.dart' as _i3;
import 'package:assoshare/domain/repositories/filter_repository.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFilterEntity_0 extends _i1.SmartFake implements _i2.FilterEntity {
  _FakeFilterEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AdRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdRepository extends _i1.Mock implements _i3.AdRepository {
  @override
  _i4.Future<_i5.Result<void>> postAd(_i6.PostAdEntity? ad) =>
      (super.noSuchMethod(
        Invocation.method(
          #postAd,
          [ad],
        ),
        returnValue:
            _i4.Future<_i5.Result<void>>.value(_i7.dummyValue<_i5.Result<void>>(
          this,
          Invocation.method(
            #postAd,
            [ad],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i5.Result<void>>.value(_i7.dummyValue<_i5.Result<void>>(
          this,
          Invocation.method(
            #postAd,
            [ad],
          ),
        )),
      ) as _i4.Future<_i5.Result<void>>);

  @override
  _i4.Future<_i5.Result<List<_i8.AdEntity>>> fetchAdsByUserId(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAdsByUserId,
          [uid],
        ),
        returnValue: _i4.Future<_i5.Result<List<_i8.AdEntity>>>.value(
            _i7.dummyValue<_i5.Result<List<_i8.AdEntity>>>(
          this,
          Invocation.method(
            #fetchAdsByUserId,
            [uid],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i5.Result<List<_i8.AdEntity>>>.value(
                _i7.dummyValue<_i5.Result<List<_i8.AdEntity>>>(
          this,
          Invocation.method(
            #fetchAdsByUserId,
            [uid],
          ),
        )),
      ) as _i4.Future<_i5.Result<List<_i8.AdEntity>>>);

  @override
  _i4.Future<_i5.Result<void>> deleteAd(String? adId) => (super.noSuchMethod(
        Invocation.method(
          #deleteAd,
          [adId],
        ),
        returnValue:
            _i4.Future<_i5.Result<void>>.value(_i7.dummyValue<_i5.Result<void>>(
          this,
          Invocation.method(
            #deleteAd,
            [adId],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i5.Result<void>>.value(_i7.dummyValue<_i5.Result<void>>(
          this,
          Invocation.method(
            #deleteAd,
            [adId],
          ),
        )),
      ) as _i4.Future<_i5.Result<void>>);

  @override
  _i4.Future<_i5.Result<List<_i8.AdEntity>>> searchAd(
    String? query,
    int? page,
    _i2.FilterEntity? filter,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchAd,
          [
            query,
            page,
            filter,
          ],
        ),
        returnValue: _i4.Future<_i5.Result<List<_i8.AdEntity>>>.value(
            _i7.dummyValue<_i5.Result<List<_i8.AdEntity>>>(
          this,
          Invocation.method(
            #searchAd,
            [
              query,
              page,
              filter,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i5.Result<List<_i8.AdEntity>>>.value(
                _i7.dummyValue<_i5.Result<List<_i8.AdEntity>>>(
          this,
          Invocation.method(
            #searchAd,
            [
              query,
              page,
              filter,
            ],
          ),
        )),
      ) as _i4.Future<_i5.Result<List<_i8.AdEntity>>>);

  @override
  _i4.Future<_i5.Result<List<String>>> getAdSuggestions(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAdSuggestions,
          [query],
        ),
        returnValue: _i4.Future<_i5.Result<List<String>>>.value(
            _i7.dummyValue<_i5.Result<List<String>>>(
          this,
          Invocation.method(
            #getAdSuggestions,
            [query],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i5.Result<List<String>>>.value(
            _i7.dummyValue<_i5.Result<List<String>>>(
          this,
          Invocation.method(
            #getAdSuggestions,
            [query],
          ),
        )),
      ) as _i4.Future<_i5.Result<List<String>>>);
}

/// A class which mocks [FilterRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilterRepository extends _i1.Mock implements _i9.FilterRepository {
  @override
  _i4.Future<_i2.FilterEntity> retrieveFilters() => (super.noSuchMethod(
        Invocation.method(
          #retrieveFilters,
          [],
        ),
        returnValue: _i4.Future<_i2.FilterEntity>.value(_FakeFilterEntity_0(
          this,
          Invocation.method(
            #retrieveFilters,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.FilterEntity>.value(_FakeFilterEntity_0(
          this,
          Invocation.method(
            #retrieveFilters,
            [],
          ),
        )),
      ) as _i4.Future<_i2.FilterEntity>);

  @override
  _i4.Future<void> saveFilters(_i2.FilterEntity? filter) => (super.noSuchMethod(
        Invocation.method(
          #saveFilters,
          [filter],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearLocationFilters() => (super.noSuchMethod(
        Invocation.method(
          #clearLocationFilters,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
