// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_sta.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaSB2iXmHIS4e0rxkOyQlfF4gMKzPMwfw',
    appId: '1:682904294514:web:72a5474425db725ead5eeb',
    messagingSenderId: '682904294514',
    projectId: 'bpm-sta',
    authDomain: 'bpm-sta.firebaseapp.com',
    storageBucket: 'bpm-sta.appspot.com',
    measurementId: 'G-6RS2B96RJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEmoh4Su36JPgl7olwMxCpNTsuPRcoAl4',
    appId: '1:682904294514:android:754c884091ee0cd2ad5eeb',
    messagingSenderId: '682904294514',
    projectId: 'bpm-sta',
    storageBucket: 'bpm-sta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbTq6sQl0JTsP3KicTVAS6RgnNh89hIR0',
    appId: '1:682904294514:ios:0135860904f1cc88ad5eeb',
    messagingSenderId: '682904294514',
    projectId: 'bpm-sta',
    storageBucket: 'bpm-sta.appspot.com',
    iosBundleId: 'com.bpm.bpm.sta',
  );
}
