// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTfy2qdodBSrQDPyYssiFpouU3hA7SNN0',
    appId: '1:1093219269460:web:e3f5c23b64fd98fb9366c1',
    messagingSenderId: '1093219269460',
    projectId: 'bpm-dev-71dd4',
    authDomain: 'bpm-dev-71dd4.firebaseapp.com',
    storageBucket: 'bpm-dev-71dd4.appspot.com',
    measurementId: 'G-W7SN3B0J7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaynFwXWMF_HqeCAtQNeW0z5xXI8gsUsM',
    appId: '1:1093219269460:android:5927f610ec01405f9366c1',
    messagingSenderId: '1093219269460',
    projectId: 'bpm-dev-71dd4',
    storageBucket: 'bpm-dev-71dd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI3AUJdQU4AvfKbhiJxKg1OQWL7aNlOxg',
    appId: '1:1093219269460:ios:0985dd1ee636ae209366c1',
    messagingSenderId: '1093219269460',
    projectId: 'bpm-dev-71dd4',
    storageBucket: 'bpm-dev-71dd4.appspot.com',
    iosBundleId: 'com.rennes.bpm.dev',
  );

}