// Mocks generated by Mockito 5.4.4 from annotations
// in assoshare/test/presentation/blocs/publish_ad/pick_photos_bloc/pick_photos_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:assoshare/domain/usecases/publish_ad/pick_photo_from_camera_use_case.dart'
    as _i2;
import 'package:assoshare/domain/usecases/publish_ad/pick_photos_from_gallery_use_case.dart'
    as _i5;
import 'package:image_picker/image_picker.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PickPhotoFromCameraUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPickPhotoFromCameraUseCase extends _i1.Mock
    implements _i2.PickPhotoFromCameraUseCase {
  MockPickPhotoFromCameraUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.XFile?> execute() => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i3.Future<_i4.XFile?>.value(),
      ) as _i3.Future<_i4.XFile?>);
}

/// A class which mocks [PickPhotosFromGalleryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPickPhotosFromGalleryUseCase extends _i1.Mock
    implements _i5.PickPhotosFromGalleryUseCase {
  MockPickPhotosFromGalleryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.XFile>> execute() => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i3.Future<List<_i4.XFile>>.value(<_i4.XFile>[]),
      ) as _i3.Future<List<_i4.XFile>>);
}
