// Mocks generated by Mockito 5.4.4 from annotations
// in assoshare/test/presentation/blocs/profile_ads/profile_ads_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:assoshare/core/domain/entities/result.dart' as _i4;
import 'package:assoshare/domain/entities/ad/ad_entity.dart' as _i7;
import 'package:assoshare/domain/entities/ad/post_ad_entity.dart' as _i5;
import 'package:assoshare/domain/entities/filter/filter_entity.dart' as _i8;
import 'package:assoshare/domain/repositories/ad_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AdRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdRepository extends _i1.Mock implements _i2.AdRepository {
  @override
  _i3.Future<_i4.Result<void>> postAd(_i5.PostAdEntity? ad) =>
      (super.noSuchMethod(
        Invocation.method(
          #postAd,
          [ad],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #postAd,
            [ad],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #postAd,
            [ad],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<List<_i7.AdEntity>>> fetchAdsByUserId(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAdsByUserId,
          [uid],
        ),
        returnValue: _i3.Future<_i4.Result<List<_i7.AdEntity>>>.value(
            _i6.dummyValue<_i4.Result<List<_i7.AdEntity>>>(
          this,
          Invocation.method(
            #fetchAdsByUserId,
            [uid],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i4.Result<List<_i7.AdEntity>>>.value(
                _i6.dummyValue<_i4.Result<List<_i7.AdEntity>>>(
          this,
          Invocation.method(
            #fetchAdsByUserId,
            [uid],
          ),
        )),
      ) as _i3.Future<_i4.Result<List<_i7.AdEntity>>>);

  @override
  _i3.Future<_i4.Result<void>> deleteAd(String? adId) => (super.noSuchMethod(
        Invocation.method(
          #deleteAd,
          [adId],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #deleteAd,
            [adId],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #deleteAd,
            [adId],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<List<_i7.AdEntity>>> searchAd(
    String? query,
    int? page,
    _i8.FilterEntity? filter,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchAd,
          [
            query,
            page,
            filter,
          ],
        ),
        returnValue: _i3.Future<_i4.Result<List<_i7.AdEntity>>>.value(
            _i6.dummyValue<_i4.Result<List<_i7.AdEntity>>>(
          this,
          Invocation.method(
            #searchAd,
            [
              query,
              page,
              filter,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i4.Result<List<_i7.AdEntity>>>.value(
                _i6.dummyValue<_i4.Result<List<_i7.AdEntity>>>(
          this,
          Invocation.method(
            #searchAd,
            [
              query,
              page,
              filter,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<List<_i7.AdEntity>>>);

  @override
  _i3.Future<_i4.Result<List<String>>> getAdSuggestions(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAdSuggestions,
          [query],
        ),
        returnValue: _i3.Future<_i4.Result<List<String>>>.value(
            _i6.dummyValue<_i4.Result<List<String>>>(
          this,
          Invocation.method(
            #getAdSuggestions,
            [query],
          ),
        )),
        returnValueForMissingStub: _i3.Future<_i4.Result<List<String>>>.value(
            _i6.dummyValue<_i4.Result<List<String>>>(
          this,
          Invocation.method(
            #getAdSuggestions,
            [query],
          ),
        )),
      ) as _i3.Future<_i4.Result<List<String>>>);
}
